# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ucellphone',
            field=models.CharField(default='086', max_length=15, verbose_name='手机'),
        ),
    ]
