# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20171109_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='isactive',
            field=models.BooleanField(default=False, verbose_name='是否为当前地址'),
        ),
    ]
