# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='isdelete_order',
            field=models.BooleanField(default=False, verbose_name='是否删除订单'),
        ),
    ]
